# ------------------ 
# ModelArguments
# ------------------ 
model_name_or_path: allenai/scibert_scivocab_uncased
# ? model_type
# ? config_name

# ? tokenizer_name
# ? cache_dir
# ? use_fast_tokenizer
# ? model_revision
# ? use_auth_token